In [3]:
from google.colab import files



In [4]:
uploaded = files.upload()

Saving bank.csv to bank.csv


In [76]:
import io
import pandas as pd
bankdf = pd.read_csv(io.BytesIO(uploaded['bank.csv']))
bankdf.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [77]:
bankdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [78]:
## Feature Elimination

bankdf.drop(['RowNumber','CustomerId', 'Surname'], axis=1, inplace=True)


In [79]:
bankdf.head()

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [80]:
##Check for missing values in X

bankdf.isnull().sum()


CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [81]:
#if we have any missing values at all.
bankdf.isnull().values.any()

False

In [82]:

X = bankdf.iloc[:,0:10].values
y = bankdf.iloc[:, 10].values



In [84]:
print(X[:10,:], '\n')
print(y[:10])


[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]
 [645 'Spain' 'Male' 44 8 113755.78 2 1 0 149756.71]
 [822 'France' 'Male' 50 7 0.0 2 1 1 10062.8]
 [376 'Germany' 'Female' 29 4 115046.74 4 1 0 119346.88]
 [501 'France' 'Male' 44 4 142051.07 2 0 1 74940.5]
 [684 'France' 'Male' 27 2 134603.88 1 1 1 71725.73]] 

[1 0 1 0 0 1 0 1 0 0]


In [85]:

# convert Geography & Gender columnns into cateogrical data and also hot encoding
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
import numpy as np


In [86]:

#Gender
labelencoder1 = LabelEncoder()
X[:, 2] = labelencoder1.fit_transform(X[:, 2])




In [88]:

print(X[:10,:], '\n')
print(y[:10])

[[619 'France' 0 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 0 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 0 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 0 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 0 43 2 125510.82 1 1 1 79084.1]
 [645 'Spain' 1 44 8 113755.78 2 1 0 149756.71]
 [822 'France' 1 50 7 0.0 2 1 1 10062.8]
 [376 'Germany' 0 29 4 115046.74 4 1 0 119346.88]
 [501 'France' 1 44 4 142051.07 2 0 1 74940.5]
 [684 'France' 1 27 2 134603.88 1 1 1 71725.73]] 

[1 0 1 0 0 1 0 1 0 0]


In [89]:
# Geography column. First create ColumnTrasfromer object
ct = ColumnTransformer([("encoder", OneHotEncoder(), [1])], remainder = 'passthrough')
#Once we have constructed this columnTransformer object, we have to fit and transform the dataset to label encode and one hot encode the column.
X = np.array(ct.fit_transform(X), dtype=np.str)

In [91]:
#print(X[:10,:], '\n')
#print(y[:10])
print(X[0])

['1.0' '0.0' '0.0' '619' '0' '42' '2' '0.0' '1' '1' '1' '101348.88']


In [92]:
from sklearn.model_selection import train_test_split

In [93]:
# Split Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=1)

In [94]:
# Normalization of data.
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
X_train = standardScaler.fit_transform(X_train)
X_test = standardScaler.transform(X_test)

In [95]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(7000, 12)
(3000, 12)
(7000,)
(3000,)


In [96]:
# Create Model
import keras
import sys
from keras.models import Sequential #to initialize NN
from keras.layers import Dense #used to create layers in NN

In [98]:
classifier = Sequential()
#Input Layer
#Tip: units should be the average of nodes in the input layer (12 nodes) and the number of nodes in the output layer (1 node). For this case is 12+1/2 = 6#
classifier.add(Dense(units = 6, activation = 'relu', input_dim = 12 ))
# Hidden Layer
classifier.add(Dense(units = 6,  activation = 'relu'))
# output layer
classifier.add(Dense(units = 1,  activation = 'sigmoid'))
##sgd = optimizer.Adam(lr=0.001) 
classifier.compile(optimizer ='adam', loss= 'binary_crossentropy', metrics=['accuracy'])
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100  )

Epoch 1/100
700/700 [==============================] - 1s 2ms/step - loss: 0.5763 - accuracy: 0.6999
Epoch 2/100
700/700 [==============================] - 1s 2ms/step - loss: 0.4471 - accuracy: 0.8030
Epoch 3/100
700/700 [==============================] - 1s 2ms/step - loss: 0.4269 - accuracy: 0.8139
Epoch 4/100
700/700 [==============================] - 1s 2ms/step - loss: 0.4127 - accuracy: 0.8210
Epoch 5/100
700/700 [==============================] - 1s 2ms/step - loss: 0.3958 - accuracy: 0.8311
Epoch 6/100
700/700 [==============================] - 1s 2ms/step - loss: 0.3772 - accuracy: 0.8416
Epoch 7/100
700/700 [==============================] - 1s 2ms/step - loss: 0.3635 - accuracy: 0.8483
Epoch 8/100
700/700 [==============================] - 1s 2ms/step - loss: 0.3547 - accuracy: 0.8521
Epoch 9/100
700/700 [==============================] - 1s 2ms/step - loss: 0.3510 - accuracy: 0.8534
Epoch 10/100
700/700 [==============================] - 1s 2ms/step - loss: 0.3479 - accura

In [ ]:
# Prediction came to 86%

In [99]:
y_pred = classifier.predict(X_test)

In [100]:
#Threshold of 50%
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
# get Accuracy

In [101]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2276,   97],
       [ 336,  291]])

In [103]:
accuracy =(2276+291)/(2276+97+336+291)
accuracy

0.8556666666666667